name: First Workflow
on: [push]
jobs:
    run-shell-commands:
        runs-on: ubutu-latest
        name: Run Shell Commands
        steps:
            - name: echo a string
              run: echo  "Hello World"
            - name: Multiline command
              run : |
                node -V
                npm -V